services:
  beets:
    container_name: beets
    image: lscr.io/linuxserver/beets:latest
    restart: "no"
    networks:
      - music
      - traefik
    ports:
      - 8337:8337
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DATADIR/beets:/config
      - $MUSICDIR:/music
      - $DOWNLOADSDIR:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beets-secure.rule=Host(`beets.$DOMAIN`)"
      - "traefik.http.routers.beets-secure.entrypoints=https"
      - "traefik.http.routers.beets-secure.tls=true"
      - "traefik.http.routers.beets-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.beets-secure.service=beets-service"
      - "traefik.http.services.beets-service.loadbalancer.server.port=8337"
      - "traefik.http.routers.beets-secure.middlewares=sslheader@docker"

networks:
  music:
    external: true
  traefik:
    external: true
