include:
  - ./aerofoil/docker-compose-aerofoil.yml
  - ./transmission/docker-compose-transmission.yml
  - ./prowlarr/docker-compose-prowlarr.yml
  - ./flaresolverr/docker-compose-flaresolverr.yml

networks:
  traefik:
    external: true
