services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "1883:1883"
    environment:
      - TZ=$TZ
    volumes:
      - $DATADIR/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

networks:
  traefik:
    external: true

volumes:
  mosquitto_data:
  mosquitto_log:
