[global]
   workgroup = WORKGROUP
   server string = Pi Server
   security = user
   passdb backend = tdbsam
   map to guest = never
   log level = 1
   max log size = 50

[Docker]
   path = /mnt/docker
   valid users = tjelite1986
   read only = no
   browsable = yes
   create mask = 0664
   directory mask = 0775

[Downloads]
   path = /mnt/downloads
   valid users = tjelite1986
   read only = no
   browsable = yes
   create mask = 0664
   directory mask = 0775

[Music]
   path = /mnt/music
   valid users = tjelite1986
   read only = no
   browsable = yes

[Nintendo_Games]
   path = /mnt/nintendo/games
   valid users = tjelite1986
   read only = no
   browsable = yes

[Nintendo_Software]
   path = /mnt/nintendo/software
   valid users = tjelite1986
   read only = no
   browsable = yes

[Nintendo_Modding]
   path = /mnt/nintendo/modding
   valid users = tjelite1986
   read only = no
   browsable = yes

[Dockdata]
   path = /mnt/dockdata
   valid users = tjelite1986
   read only = no
   browsable = yes

[Appbuilds]
   path = /mnt/appbuilds
   valid users = tjelite1986
   read only = no
   browsable = yes

[Roms]
   path = /mnt/roms
   valid users = tjelite1986
   read only = no
   browsable = yes
