include:
  - ./elitetube/docker-compose-elitetube.yml
  - ./tidsrapport/docker-compose-tidsrapport.yml
  # - ./dashboard/docker-compose-dashboard.yml    # ej public än
  # - ./forsaljning/docker-compose-forsaljning.yml # ej public än

networks:
  traefik:
    external: true
