services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      TZ: $TZ
    networks:
      - traefik
    ports:
      - 8191:8191

networks:
  traefik:
    external: true
