services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    volumes:
      - /home/thomas/dockdata2/homer:/www/assets
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer-secure.rule=Host(`homer.$DOMAIN`)"
      - "traefik.http.routers.homer-secure.entrypoints=https"
      - "traefik.http.routers.homer-secure.tls=true"
      - "traefik.http.routers.homer-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.homer-service.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
